GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Quantumania",
    "author": "Pedro Salinas",
    "url": "https://quantumania.es",
    "likes": 13
}

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "user": "Nuria",
    "username": "nlin4575",
    "password": "testpass"
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "user": "Nuria",
    "username": "nlin4575"
}
